### ISSUE TITLE
Dependency on GitHub only package  bigmemoryExt 

### ISSUE THREAD

**Issue by nathansam** [marioni-group/MethylPipeR#4]
`MethylPipeR` currently depends on [`bigmemoryExt`](https://github.com/cdeterman/bigmemoryExt) which also requires a forked version of the `bigmemory` package not on CRAN. As all dependencies for a CRAN package have to be on either CRAN or Bioconductor, MethylPipeR cannot be submitted to CRAN in this state. 

If the dependencies are absolutely necessary, it may be possible to simply add the necessary code from these packages to MethylPipeR whilst respecting the restrictions of the open source license these packages are both under (you would need to add attribution).

**Comment by MoMaz123** [comment]
I have  the  same  issues, 
see  below

Installing package into ‘C:/Users/XXXX/AppData/Local/R/win-library/4.2’
(as ‘lib’ is unspecified)
ERROR: dependency 'bigmemoryExt' is not available for package 'MethylPipeR'
* removing 'C:/Users/XXXX/AppData/Local/R/win-library/4.2/MethylPipeR'
Warning messages:
1: package ‘bigmemoryExt’ is not available for this version of R

**Comment by KyleRowe1230** [comment]
I have the same problem, any solution?

**Comment by nathansam** [comment]
As a workaround for now, you'll have to install a fork of `{bigmemory}` maintained by the developer of the bigmemoryExt package and then install `{bigmemoryExt}` from GitHub. You can then install `{MethylPipeR}`. 

```R
# Install fork of bigmemory
devtools::install_github('cdeterman/bigmemory')
# install bigmemoryExt (GitHub only)
devtools::install_github('cdeterman/bigmemoryExt')
# install MethylPipeR
devtools::install_github("marioni-group/MethylPipeR")
```

**Comment by KyleRowe1230** [comment]
thanks！

**Comment by YipengC** [comment]
Updated so that bigmemoryExt is no longer required for installation. The package can use bigmemory from CRAN.
